### ISSUE TITLE
Express app crashes when the SDK throws an error

### ISSUE THREAD

**Issue by dalbinaco** [directus/directus-sdk-javascript#12]
I was testing some 404 and timeout scenarios in a Express middleware using this request:

```javascript
import directus from '../directus-sdk'

function validateEmail(req, res) {
  const email = req.query.email
  const hash = aes('encrypt', email)
  directus.getItems('indicadores', {
    'in[email]': email,
    'status': 1
  }).then(result => {
    res.send({
      success: true,
      exists: result.meta.total != 0,
      hash: result.meta.total != 0 ? hash : null
    })
  }).catch(error => {
    console.log(error)
    res.send({
      success: false
    })
  })
}
```

So I stopped the Directus server to simulate a timeout scenario and got this logged, and then Express crashed:

```javascript
Production Express server running at localhost:3000
C:\labs\indique\node_modules\directus-sdk-javascript\index.js:114
                if (r) throw new Error(r);
                       ^

Error: Error: connect ETIMEDOUT 52.67.2.126:80
    at Request.r [as _callback] (C:\labs\indique\node_modules\directus-sdk-javascript\index.js:114:30)
    at self.callback (C:\labs\indique\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\labs\indique\node_modules\request\request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by rijkvanzanten** [comment]
Hi @dalbinaco, thanks for the heads up! I've pushed a new version which uses native promises reject for all errors. Could you try out the beta version of `v2.0.0` by running `npm install directus-sdk-javascript@beta`?

Let me know if that fixes your problem 😃

**Comment by rijkvanzanten** [comment]
We have replaced `request` with `axios` which `rejects` a promise on a connection error. It works just like expected on my end now.

Please reopen this issue if this fix didn't fix it for you!

**Comment by dalbinaco** [comment]
@rijkvanzanten Yes, it is fixed! Thanks.
