### ISSUE TITLE
createFile is throwing a 500 Internal Server Error.

### ISSUE THREAD

**Issue by rosswaycaster** [directus/directus-sdk-javascript#5]
I've tried this on both 6.3.6 and 6.3.7

My code running on node:

`client.createFile({
                name: 'test.png',
                type: 'image/png',
                data: 'base64stringhere'
            }, function(err, data){
                if (err) {
                    console.log(err);
                    throw err;
                }
                console.log(data);
            });
`

But it returns an error:
`http://directusurl.com/api/1.1/tables/directus_files/rows returned internal server error (500)`

**Comment by rijkvanzanten** [comment]
Hi @rosswaycaster, thanks for reporting this! 

@WellingGuzman Could this be an issue in core? I'm getting this result when trying to create a file 'by hand' through the api endpoint:

```html
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in
<b>Unknown</b> on line
<b>0</b>
<br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in
<b>Unknown</b> on line
<b>0</b>
<br />
<br />
<b>Warning</b>:  session_start(): Cannot send session cache limiter - headers already sent in
<b>/Users/rijk/Development/directus/api/core/Directus/Auth/RequestNonceProvider.php</b> on line
<b>49</b>
<br />
<br />
<b>Fatal error</b>:  Uncaught exception 'ErrorException' with message 'Cannot modify header information - headers already sent' in /Users/rijk/Development/directus/api/core/Directus/View/ExceptionView.php:78
Stack trace:
#0 [internal function]: Slim\Slim::handleErrors(2, 'Cannot modify h...', '/Users/rijk/Dev...', 78, Array)
#1 /Users/rijk/Development/directus/api/core/Directus/View/ExceptionView.php(78): header('Content-type: a...')
#2 /Users/rijk/Development/directus/api/core/Directus/Exception/ExceptionHandler.php(58): Directus\View\ExceptionView::exceptionHandler(Object(Directus\Application\Application), Object(ErrorException))
#3 [internal function]: Directus\Exception\ExceptionHandler-&gt;handleException(Object(ErrorException))
#4 {main}
  thrown in
<b>/Users/rijk/Development/directus/api/core/Directus/View/ExceptionView.php</b> on line
<b>78</b>
<br />
```

**Comment by WellingGuzman** [comment]
Hey @rosswaycaster + @rijkvanzanten ,

The issue with `Automatically populating $HTTP_RAW_POST_DATA is deprecated` is a PHP issue that needs to be disabled by adding `always_populate_raw_post_data = -1` in php.ini

Are both experimenting the same issue?

**Comment by rijkvanzanten** [comment]
Ah, you're right. This was also returning http 200 sooo I wasn't paying attention ^^

Anyhow, the 500 server error is `Argument #1 is not an array`

```json
{
  "code": 2,
  "class": "ErrorException",
  "message": "array_merge(): Argument #1 is not an array",
  "file": "/Users/rijk/Development/directus/api/routes/A1/Files.php",
  "line": 43,
  "trace": [
    {
      "function": "handleErrors",
      "class": "Slim\\Slim",
      "type": "::",
      "args": [
        2,
        "array_merge(): Argument #1 is not an array",
        "/Users/rijk/Development/directus/api/routes/A1/Files.php",
        43,
        {
          "id": null,
          "app": {
            "container": {}
          },
          "acl": {},
          "ZendDb": {},
          "requestPayload": {
            "data": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAABbCAYAAACRd3yIAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDozNERDQzI3OUE4RkUxMUU0OUIyQUU4NEFBRUQ4MUUyMSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDozNERDQzI3QUE4RkUxMUU0OUIyQUU4NEFBRUQ4MUUyMSI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjM0RENDMjc3QThGRTExRTQ5QjJBRTg0QUFFRDgxRTIxIiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjM0RENDMjc4QThGRTExRTQ5QjJBRTg0QUFFRDgxRTIxIi8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+kFVc8gAAGjpJREFUeNrsnQl8XUW5wGfmLHfJ2i3dabOVtlArtM9XLLI8QCn4VLbqY3myCYoPRauIPBHqD8GnqKxPEXn0KatYi7zytKBdLAWspXRJS9ssBCqhaZImubnr2cZv5sw59+QmaXLT5C7NnfbLzJm7nTvnf7/vm2+Wg9EYT9/b3+kjCNVghGsgrwKZhhGaQTCqgPIEqC+HnEkRiAyPIcgR1PMcJAF1Yci7uWDcDseHoNwCeQvkjSBN8PymS2qLE2OlXWVUSE+BXHIMr/cJmTDI86w19WEGWR3IboBuG0F46wW1Ra3HY6PigsbqnAYXeh9olBLiaiPIcR/NlHwspR57HgeN5XmO93X9vQ+vew/Km+HzNkK+8dyaooYCWMdJunt/5w1w4R/NElju54nnN0P9S5C/xED7WE0wVgArj9M9+7uehcb4bA6A5a2PMMBUgn8P+QuLqgLRAlh5lh5uCpWGdetv0CBzcggs+9hiZRr1SdIfoKfx2PxK/7oCWHmUHmrsro7qdAsUJxNMkcRbhyApm2BRWxClkGMkQVki+KBfwasUgu+vme07UgArD9LPG7sWdevWn0SYAWEAReIXmgothrMCFgawWC1hOYOL8sfjfhW/6FOklZWz1L0FsHI8PdbYtaRLN/+PUjwROBFgYa65MNNkHBP74ksekEYVLHYMGouD5ZpHZAMPR34Zb1AV8t1ZleprudCGpIBR7/RMQ89cv4mXjUPSuxKl7aZpIS4WCLWQZVFbqBCop5C74rwRHakzon21APVcOWzba02n50Qi5qtN++Mb3m+OLy5orBxIv60PF4M6uFqj9GrDRIsMuHJMTPifMPWDMYvOJoTwaDIWWoo4JhI7mgslNRh2tJutbdjzkKhLX2NRW1OlaCyJJjUD4fWIm0hhNi2/j6zzqeSmKZVqcwGsDKcX68MzTYS+AvIFE9EyAy4aKCfkAQvpUKebxkHNNCdDc6kMIBss26mXICceqBzonLqkuXTAwi5EEk2WjwYWAwdT5L4HFn4WBwl7wHJMpOOHYZwI+MnjsoJXVFSq8QJYo5z+WB8hANKvAajlIDIIMgVIDC4uHrDYsW5ZMWrq3YZpTXHAkj0gMa3EoSNEHCMXMBsgUUYebSZegwVgSRj797FYPRaOvK3BPM/3aCxvL5KVZYJb/UH81Yoa33MFH2sU0/m1RfC7Rm+h1LFSbPcCcT8/N6gPWJI8xcRSu2FZnQnNQAndRBrYTk03ILdFZ8csNyE3DQQgIsMyuTBfzT62fTbbR2O+mpX02bivJjwr/oeroD4uG07DhzNNOjnWYz17aG98Q0eTNrmgsUbfFF4G2moVSJBrLHYRqK29bC1FXY1lC4MCtBqr17UOFbAA1TdRAnXENBFoBi5cYzFTKTSabT5Jsowc7UVs38xjOh2/TXI0GqW2KaXY1VjEYw4lp8dJPRrM6q2xvPWE4JC/iNwyYY76RAGsUUxr6sPzAKhnAaYPecGyzSNCGmgWDUBiWsYLFtNAOjOVmqHJut7uIzSoIKlclQkLYHIzyUCQJQEZg4TYZlDuz5QKkD44Eom/uudQm9+n7r1qadXHAQjMQgoOWERoMuKYQ5TiY7kOvADK8tRbwkxB2R8kf5D95NKyKiVaAGv0eoV+gOlOAGkFgKV4wTJEWYMHmGnTTdoLLANMnw4m0dABwIRhSobV6Zeo4ZexL6DIPgDNH1RkIvFeJXahYxqlJ2LoXT3xnubWkHHwg26p9UgsKAeKYiUVE676wSerlwDHdxDHsbdQL7AkYS9d5x319rFwr16iqBeW1XmOrOJDviJycWmN+noBrFFMT9f3zAVuHgSwzksFy3HwGVjMr0owv4oB5gFL1yxe1hMgoNoMXjaYb2VZ4HSZFjUNDV4b0+RYBBQd+GnsEvhLilGwvCSmlhTfA/7QjzfdOCe2uSG6Gx48mSDHeRemjV0yobF4z9IJQ6QLFnJ7lbq/VPpW6Rz1p8cdWHduaLkFwze868yp9+fC+aw6EFoCIN0F8olUsGxTKSAD85gAULQ4OPJCNIAlFSzDYNDpcEy5YQP1hSRFRWrAjyRV7QKYHgV54OVraj5gn/+XxuhMePv3sLj4th/l+EzY7XU5vUPW68SoN0AcLAv19rFEHfaCJUQtllbLfrw8WK1YeQ/WL7e3qZOL5derx6unmpTSbS2Jy65ZOGF1rmiwXxwIzQWwrgWQrgKZkgoWz0FrmaYthtE79wrr/RneOoNugfxpkF+tvaIq7P3cTQ3R6+HCPJYMJ3j8JJSEyAHLdvKT/lNSS2HXyXfrLc9AuuV19jFSgni3GiRnBGqUrrwGa/XeI29Wj1dOdc4iqtHE20e0JdctnLgjl0zkQwe6JYDoIwDTMmCCmcmFUA4MBNYA0g5gbYJ8I8iLz180672BPm9jQ/QJuOBX9xpr9GodTzzLjYN5nPckSP2AxUHCXAM6YNlOvhhBUHCrXEqWBmuVxrwE6xfbDn9/4TT/7ckTsUPP3XGzp6FTX/ylUycdyFVf7N79XQAaPRHAmgdgTQVQZoD4Aawg5CoIM28dDCaQ/SD7/ue86S1DfX8A6224yHNdsKgnKk89PpUwkRIlfHDcGepxzaA1CFi9NJnHT5Nxj1yOzw3WqlvzCqwfbG4pWjgl0FHkIz6EUJ+AZI9m9jR2GR+9eVFF3VjrQGxqikwE161NQrgXTMiJcXGn3RN2YLMtwGdLnU3BnXQgn+gipiW0E+9RMrAwdX0wF1ZnFgXUUxnF1XHkAoBrQ95E3gOq9F0ZuuMJMCNcTCFQZj0tn0xKZpfJ2x7efviysQYWwfhjSPT87Og7TWoA7Mx1EHUsyCX1rxv4YwoAFACRsatCWEZJ0kK4lalvY1C/1mmuizRoF+YNWEEFX5RgPSrTQppp586xXWa/QuybXa489+iOtqce2H54zCxTgz7Mv/DpN9jmh2KcvPDUo93JEO0Ne7kPtJGf9P98Tx1FKaAZSNGOmGsiDYkL8wIsn4JnaAYVQUch/BjZYtjH4L/gKcXS5RP8pPWBN1uvHQtgGRZaSoEqy0LuHC+LuorLvuJkGB4M/DRJkLijo7RfAvt5nYWURCfA1Zg4L+d9rCfrDpugkUTz9FbT3kLqcShBW0O69TPwDu5dcWqFdrxB9fp7sbJQzGwDV1yREHKnQkt8lihm43wippW6TA33M2N14HrM1mPHqYiNOcM+8GyLun4WFSRTLMoKTqjj8RnFVf6tOQvW47taDYUQKfXTU5143PuPW4RuuxHS6W6N0jVgOZ+5ddHk42KR51/eid4UjpuP2APWzqC0M/+LgrIhveZtDRcsHgtjajACcJk0CRal7tiiCxa8yBJRfqzSqDJBWlg8y9+Qk2A9sPWDcNBHigbUwmLe+MCP9z7WLBYCowcNCzfAAzvAmu4ES/q32z5c0ZxPYL18ILwFXICPOnO7iDsbAhQGEZMK0ciAxQFl2ikGf+IWlIkIO9gQUUyFj5cEi9VhP+6QJ5LK0un+npwDa+Xmv9dNKJJP6mvycN+TwoOZSPvI7lUipHO3AEOnBnKCE/CWLQmK6+GavAOmpBmOm1nOZOXccYdyBapXmyPzDofNOoCISHzmgw0NG7D2ScnZDyMKllPHIr0AGDORxBJACS/MEqaQj5tL0LLFoE3L8ZllUwJ/GcSly3wKxa01xX7rJG9g1HEpcQpZfY/t5zOHvwfoiRiYuQu2lsN8vhGIO9/cB+VKKFf29wu6a39nAp7aABdzH5ibPdAYe1SCt36lpizjmi6coPeBiSfOeA37HqyoyMPz1dNytKEBGDDMhmCNT6NF1BRrNiSbEtBUCEHPEs6wAzTXlpw0hTesfdc3bZzcqcosyjKwiUv1udiPqQdUUrfGtBPmsRo+SY7YQCXBSoXsKM9BnuVZziwChNtVCb2lYvS6ivG6cgX/9dITSs3Rao8NTZGzW7r0P2MecrInC/olgopVMV9rAA00Uhqrv3WSVHjxzMeiYjyJ5XC8snyy/66cBIulL//x3dsmlUr34qOaPIycGGEX2LkuDXMzRwQcowUWRskVNjziTVE3/FjfCMj4JT/Bz36usqxtpNphfWO0vDWkNYApn8B9KbB5pT4ZoCKDgpIFsJrheCGAFcpZsDhcLzdvLAuQM5MaCvfpJUY1hDritrayYco8WMlVMbzCCBK8LSCT38G1/9/PVZcfHu73f6UxUtIeMnZ1xczZDKgyoLc8IIGjToYESobBikB+VtlU/7acDTc46dqXmgmYnA1FAXwGTnGsWICwMwZOuYFSYMouWNTpIfHeE7WCEtkdlMkLQRk9dkn1+PeH+t3/cKDnnJYu87dx3SofFyRoXJEMQOH+NwXJPljt8MAnS6f5/prTAdLUdM3ad+4I+PC3JQkF2LEO3kx3DC4bFWDkKFj2chpql6FPDqbyvaBCtqkSfhW02UYD+3d+rrbEDXKvqQ+Di4yWwPOvtSx6GWgmWRFO+lF3m8kuWC8AWF8qneFLqwedM1OTl//uHT9csuVQ/BGcVoUXmjwBC3KLx314oBHeQJGIEZSljlK/P0owH1CZxE8DpbmNUebBgv4pXQuFHxXPUrcM53rmzODuby6ujF/0fLOPbyqbo6sdsVg+zxufJC+csxCV9+gk4r3wMuST82BhAevxvgvC/Kf1IC8Uz1aPaW/UnAHr08+9Mw+yh7NLjpidKTQWm7NEEElr47VcSxS5A857QF6Dc9wJ+UEQtq9WB0g7y8urRmaue06B9alnmti1+TmImjPayRPuyMfEYDLsWaVse/DrKqv8L2by83NFY/0ryBmokEbAXCdVJ/iIe+FwQXWl38r0eeQKWN8uIDECF1PyjFZQFIXiqdmAKifA+uTTTfMhW1LA4tjMtk/pPQRGTXQ3QJW1O2Hkgsa6Mid9FCeagKg7/5xSZ1Dc7q7nirfuV+1wisfBMuG8f5hV7ZkD7XJB7oBkTwN29kTgMStK3NiVJZZWmc6+Cdz8YORTSdYgC6iYm0BvsizUWD3bb45ZsC54snEKZAtzASrvnDAeJMWesANNBk+RM0HOnrPLF6PGoiZSFYL8vsz2Ihn8fqXvZ1ILvZ7tNs22xvpYLvTL3dVPHpiSIQfPKilsr0Bmfxy4sLCRbH+GOBwHA1JGe4CY9Ot0/S3bzUrGPFgecrCnki/oFJQ5Q0J20FRsuY3FkJI7rIT50E4inrlOGNsvNZqgyW0msTs09PpYB2tpTnWtnCV82GMWRQTeKaP+AJPEAlHM4EJI12nGTjuuUT5oj0lSIL2f7ebMmilc9qvG4tH2r6jYz9Pby0uWU+Y/U7Ea1DPJEAt/yru4wx7y8fhanjoOGHPuDegEsHnqGfrZRmK0l383a7qvdSxrLBa7kkYfLK8gz+CZXeD/qJhtT5N+l3f5uetzuRrMI64Gw55ZFIj7XJlKbO6apiVNYS6kbIJ1fiYccwcoaqE+kNE+kHm0Wh9HmaaYSJwETZgg4gAmrq5lZdAkgq/lMYVZT1kxhZ9Y1cBa/tMZ4ApRkwFhcd3Ituqx+MUnfO4UI8HyDjVjZ8sNu7dHHX+LJjdNsLcLSo6b8LJYHuWaTmRPqWEfkamfrq7b6jVXphxl5TT0jo4rIKvJhMayDHt/dYvdD4f5PnwTtOQ9cfjkPPd+ON5oO036Yxj3uaMNFqYRecwgr/M490l/jnr2Xhi9lEjQ/pTt2NFYMc28xZehIBXbfBYTBhA40xJK+lPOXlNE7KHOljZxwZ61jrazhSkacK6t24ukXn/MDlc4phgNcFOCEW9XcOKDQTw2wTrvvi3fiSvBRZkJIWC+2SwzfRL00lhPjW0sK4t1oYgHOMVueMReUej6WkxLUdv00UHgQigJFBK9Sf7evD9g2WEINMgbjJA5jEVpWy6AlVFTuPwX25e0dSb+M1hWnJneEttrK6YjLa4hLaHbOxprOtv0n2sy02C3jDP5reFYsNG+9UjSyUeuM+8towHNWnLmqSfWxe4oaJOake/cE6IV9Y3x7zc0xsePCY31b0/UnVPf2PZC2fQKf6Y+09ANFAsn2GYISFIIUhUJckmYJ7YXgb3rBZElZOsU+Etsj9vZ/ExErXp1CEiKQz8QZazPIHx72zRmZkYq+xC2t+utTY2J9aA5NkDFG5C/ObPa13PcgPWFZ/YXtfVoPz5wsOs6pbRYZnubZ8yXA6h6QhEkyzJSVIJMn4JUn2z34tg/lfI7Plu8pwfaiu3mYmG+ls6Nd2Gx5YoDhnM4hKuLnE30+M2YbB8vw0rj40K4An+/MbHPhgy/Bj+O16C8b1KVSvMGrNMe2kdmlJLTYgnjhr0t0Ys1TS+WfD5UNL48oy3bcbgb+TB6f2JZ4JWSYmVjwK/WyQqxFEUqBrUzH1r0FPDATtUpXQAayu9Aw/wi+6a41Nmm5BgCHjaMFttlI7tj/uznMl+IszvikY4mjS2w+DP8zNaVVylvj6TaPOZ0+oP7JoJPfCkUwSmn1ZphLabUKuE2gHflLcT8KuZA91kXKI6xWOvX35rBYa4rjIY7Qhc8tqxm02Dn//CetkCC4s9qFr0SIDsTXi/ze98QO+bl7lclIlgSdm4Xgge52bi9Ex+y7NkPPjC5MsEoh9cVNoE8D/VPFVUpu7MK1uIf77kRftU/gUYMOlvv8GklfB9x28QoAR+SoFFdgDID1vU//UjF4+l+n//e31kBcN2UsNAX4AtMI/2ARcRi1sHA4ltfY3txK+sosPYIgjnOgwWrbCX0Vij8DNyC50pmqrGMgvXhH9ZdAV3pJ52LipPTNuw1eWzFJjjLmO1D7gVo9MF65P5/rviPY/lu9x3okgOIXq5T/HXgYeGwwEL2YKgDFruvTmmRj2utPADLWWJ/iGL6X/DAo6XTfLF07O6w0ofurQtAg9/vGTzptQ0RZjumyDLKSGSwd3oa5CvH+ibfmFNufHnOuF9RjE/xSXg5NHyd+92G++uFQiSad3vyslm+7M5ge7s/iF846mBB+neQiZ4ITnIGJkkOxGY4/QTkKtBWIza14GtzyuhNtWXPwxf7EGiaS6HBdtHBQg0pQHnBiiU0fsewPEyzQdZ2tcZXdx2OTRxNsK4cOASdcajY3aouf3jplBUPnjZ5VOar3AyAfbG2dDUg9WGJ4EvYLzgdlUXEnVRZZ6CtM8yDsnmaLgbZ1dkeO23EwTr5nt3TUG7M/mQ2+EmQkx45fcozmfjAmwCwG2rLfgfFBcDJ5ZAP3kXHjm9o+4Ns8LulLYTyOE0F2XSkI/rZkdZYn0LZ3QKJTRL5Ncgpj5419aqfnTG1JdMncOOcUuv62lIG88nY/hXvOEoky50NwbfYBsjC4Gsd/KArn+FSQJ450hm9eiQDpBdlCSa2BTS7UeZvfnnOtI5caN3rADDI1qw6EHoB2XPM7mQd5qQVtNFyFlwQ3kMmfLujw50RbhKrpo/PV7jY7+Xxjq5IeEJ50W+PKdww/+7dZdAu7dBQshsu8Hb13dBBSrgg/XBDB7x+K7z+NXhsKxuC+PUFM8O53tJP1vewpjgXvtrXIF+W3N4IEDNNpLN7Qsd13juMRDQUCsdQWbEfLZwzxd0heTjhBmeWj3vvJr7YNjkrQxKBXb6HFz6mXZN5nDKlPgb56RNKi7Yfi8a6GI3s2AS74zbbu2mnENatr/vNZ2a15ONP+Ep7a8hXmDxb3zNHIehLYPpu1g0WZyVgBi1+f0FFkbioiowOtYfR4SP16LQFJ6BxxemPpTpDmixZYvdBPk3HEvPPLPuWw1TcDZYRw27Ww7f8ljEKKsc8yYVt8fl8e0/4lIklxaHhaqzNoEVOJ9ijcdLTWDHIX4HjP8Hrt0C+e+3lVTo6jtO21rgC1/lmzbQ+3xk15ndHdTkeN1A0BlornEChSByFeuLc75o7ewJadOJ0pEpD347b2eYSuZrKAQv3AgsODEnC7xAJH2B36IA3aWX3ZVIsFJisyDrbHxXkDHhLNU2N5eSPAVg3pA3WvO/tmgdg7HWgSROstyG7D8rPvXJNTQSN4bStJfpPcc08Pxw3FoWjeiWYxbJoAmDTDB00SndpUN0594QKtqDrEmJvNzlssODfIVlBm4iE1oIJXDN7lu+obR9u0svgLS8HsG6FF89OEywK9UsmFRVvTResVQDG59MEKwHHt8FjD62/vtZEhTTktLkhOhWakQVlPwXN+lEAKzgYWKCjImDd3oI23wImd3XVCeqwltuHmzUV3ux2AOUOyu/gNCSwWP0mAOusIYN14spdJ8CXaIATVtIAKwT5hZu+eOKrBUyOLb3REGXGcT40azU08QzIS5nJgqaOg/PWBXkLyB7wq5pOrPaP2ByrnoPaJwCYNQBOYIhgscfPTscJv0fELoaaWDd8eQGqkUlLaoJM2+8WkrFUMlNdF/p7goWX/j+NuOeKIT2x9s6dZ0N2RZrn9I3NN524roBE/qfSGT52HVem8ZIFg4JVfccOtvLh52mey1Nbvjz3p4VLclylu9l1HcLzWA//2qForIdA5qRxAkxV31i4DseZ1prmY67NVSC3ggzUs2R7xn96UrBk/VGd96rv7LgOnPJfktTI+cDOezcUF7/x1XkNhUtx/CY2bQac9CvBWV8KXtckyDsh3wT5qoklxV1HjWPNvv2tswCUl9ktYdIA6zNbb5n3+0LTF1K/pvCE295it9VdnWYv8J4CVIU0IFgzv7V9JmSsF5DOkPtakDsKzVlI/YI1/ZvbJ0H2J1ZM4z3YAPIV274+3yo0ZyH1AWvqijfZatL1afYA2V6Xy95cMT9UaMpC6gPWlK+/WSbM38lpvJbdluz8t7550sFCMxZSH7AqbtkWhHwNyEfSeB2LV5y181sn1xWasJAG0lhsSunZabzmPZClu7598u5C8xXS0cBan8bzmWO/uO72BQcKTVdIRwXr8P2L74P8iyBHuwVZh3jOx/d+Z0FbodkKabCEPb3CWkLwNwhByzDGMyAPw/EOjNHzkD9Rv3JhuNBchTTU9A8BBgCZ+hhqSTICSAAAAABJRU5ErkJggg==",
            "title": "Test",
            "user": "1",
            "date_uploaded": "2017-02-23 19:13:50"
          },
          "params": {
            "run_api_router": "1",
            "access_token": "RINKOhlcM4kK8bBqtI7TJfUnQNq3fGxH"
          },
          "table": "directus_files",
          "TableGateway": {
            "primaryKeyFieldName": "id",
            "memcache": null
          },
          "activityLoggingEnabled": true,
          "activityMode": 1,
          "Files": {},
          "recordData": false
        }
      ]
    },
    {
      "file": "/Users/rijk/Development/directus/api/routes/A1/Files.php",
      "line": 43,
      "function": "array_merge",
      "args": [
        false,
        {
          "title": "Test",
          "user": "1",
          "date_uploaded": "2017-02-23 19:13:50"
        }
      ]
    },
    {
      "function": "files",
      "class": "Directus\\API\\Routes\\A1\\Files",
      "type": "->",
      "args": []
    },
    {
      "file": "/Users/rijk/Development/directus/vendor/slim/slim/Slim/Route.php",
      "line": 436,
      "function": "call_user_func_array",
      "args": [
        [
          {},
          "files"
        ],
        []
      ]
    },
    {
      "file": "/Users/rijk/Development/directus/vendor/slim/slim/Slim/Slim.php",
      "line": 1305,
      "function": "dispatch",
      "class": "Slim\\Route",
      "type": "->",
      "args": []
    },
    {
      "file": "/Users/rijk/Development/directus/vendor/slim/slim/Slim/Middleware/Flash.php",
      "line": 85,
      "function": "call",
      "class": "Slim\\Slim",
      "type": "->",
      "args": []
    },
    {
      "file": "/Users/rijk/Development/directus/vendor/slim/slim/Slim/Middleware/MethodOverride.php",
      "line": 92,
      "function": "call",
      "class": "Slim\\Middleware\\Flash",
      "type": "->",
      "args": []
    },
    {
      "file": "/Users/rijk/Development/directus/api/core/Directus/Slim/CorsMiddleware.php",
      "line": 22,
      "function": "call",
      "class": "Slim\\Middleware\\MethodOverride",
      "type": "->",
      "args": []
    },
    {
      "file": "/Users/rijk/Development/directus/vendor/slim/slim/Slim/Slim.php",
      "line": 1254,
      "function": "call",
      "class": "Directus\\Slim\\CorsMiddleware",
      "type": "->",
      "args": []
    },
    {
      "file": "/Users/rijk/Development/directus/api/core/Directus/Application/Application.php",
      "line": 74,
      "function": "run",
      "class": "Slim\\Slim",
      "type": "->",
      "args": []
    },
    {
      "file": "/Users/rijk/Development/directus/api/api.php",
      "line": 1888,
      "function": "run",
      "class": "Directus\\Application\\Application",
      "type": "->",
      "args": []
    }
  ],
  "traceAsString": "#0 [internal function]: Slim\\Slim::handleErrors(2, 'array_merge(): ...', '/Users/rijk/Dev...', 43, Array)\n#1 /Users/rijk/Development/directus/api/routes/A1/Files.php(43): array_merge(false, Array)\n#2 [internal function]: Directus\\API\\Routes\\A1\\Files->files()\n#3 /Users/rijk/Development/directus/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Array, Array)\n#4 /Users/rijk/Development/directus/vendor/slim/slim/Slim/Slim.php(1305): Slim\\Route->dispatch()\n#5 /Users/rijk/Development/directus/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\\Slim->call()\n#6 /Users/rijk/Development/directus/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#7 /Users/rijk/Development/directus/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\\Middleware\\MethodOverride->call()\n#8 /Users/rijk/Development/directus/vendor/slim/slim/Slim/Slim.php(1254): Directus\\Slim\\CorsMiddleware->call()\n#9 /Users/rijk/Development/directus/api/core/Directus/Application/Application.php(74): Slim\\Slim->run()\n#10 /Users/rijk/Development/directus/api/api.php(1888): Directus\\Application\\Application->run()\n#11 {main}"
}
```

**Comment by rosswaycaster** [comment]
I was finally able to get an image to upload via Postman with these settings: 
<img width="1076" alt="screen shot 2017-02-23 at 2 06 26 pm" src="https://cloud.githubusercontent.com/assets/1231836/23276974/d38783c2-f9d1-11e6-8ce5-65328535152b.png">
I will try the Javascript SDK again, and I'll be sure to send the data, title, name, and type.

**Comment by rosswaycaster** [comment]
The Javascript SDK is still throwing a 500 error when trying to reach '/api/1/tables/directus_files/rows'

Shouldn't it be trying to POST to '/api/1/files' instead of '/api/1/tables/directus_files/rows'?

**Comment by rijkvanzanten** [comment]
Yes exactly. The SDK now tries to save the image data to the database, but doesn't upload the file. I'll start working on a fix immediately!

**Comment by rijkvanzanten** [comment]
I've just updated the module to `1.1.3` on npm. Could you let me know if it works for you @rosswaycaster?

**Comment by rosswaycaster** [comment]
@rijkvanzanten it works now! Thank you so much! 🙌🏽
